name: CICD

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ibnyassen/nodejs-app:latest .

      - name: Push Docker Image
        run: docker push ibnyassen/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image
        run: docker pull ibnyassen/nodejs-app:latest

      - name: Stop Old Container
        run: docker stop nodejs-app || true

      - name: Remove Old Container
        run: docker rm nodejs-app || true

      - name: Run Container
        run: |
          docker run -d \
            -p 4000:4000 \
            --name nodejs-app \
            --restart unless-stopped \
            -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            ibnyassen/nodejs-app:latest